Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using NetStore.Models;
using NetStore.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace NetStore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly IGenreRepository _genreRepository;

        public BookController(IBookRepository bookRepository, IGenreRepository genreRepository)
        {
            _bookRepository = bookRepository;
            _genreRepository = genreRepository;
        }

        

        public ViewResult List(string genre)
        {
            IEnumerable<Book> books;
            string currentGenre;

            if (string.IsNullOrEmpty(genre))
            {
                books = _bookRepository.AllBooks.OrderBy(p => p.BookId);
                currentGenre = "All books";
            }
            else
            {
                books = _bookRepository.AllBooks.Where(p => p.Genre.GenreName == genre)
                    .OrderBy(p => p.BookId);
                currentGenre = _genreRepository.AllGenres.FirstOrDefault(c => c.GenreName == genre)?.GenreName;
            }

            return View(new BooksListViewModel
            {
                Books = books,
                CurrentGenre = currentGenre
            });
        }

        public IActionResult Details(int id)
        {
            var book = _bookRepository.GetBookById(id);
            if (book == null)
                return NotFound();

            return View(book);
        }
    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NetStore.Controllers
{
    public class ContactController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_BookCard.cshtml
@model Book

    
                   
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="card border-0 transform-on-hover">
                        <div class="boxs project_widget">
                            <div class="pw_img">
                                <img class="img-responsive" src="@Model.ImageThumbnailUrl" alt="About the image">


                                <div class="pw_content">
                                    <div class="pw_header">
                                        <h6><a asp-controller="Book" asp-action="Details" asp-route-id="@Model.BookId">@Model.Name</a></h6>
                                        <span>$@Model.Price</span>
                                    </div>
                                    <div class="pw_meta">

                                        <small class="text-muted">@Model.ShortDescription</small>

                                    </div>
                                    <div class="addToCart">
                                        <p class="button">
                                            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                                               asp-route-bookId="@Model.BookId"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
            
    

Views/Shared/_Carousel.cshtml
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/Images/carousel1.png" alt="">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/Images/carousel2.jpg" alt="">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/Images/carousel3.png" alt="">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    @*<div class="container">*@

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="~/Images/black.png" width="100" alt="">

        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>

                @await Component.InvokeAsync("GenreMenu")
                <li class="nav-item"><a class="nav-link" asp-controller="Contact" asp-action="Index">Contact</a></li>
                @await Component.InvokeAsync("ShoppingCartSummary")
                <partial name="_LoginPartial" />

            </ul>
        </div>
    </nav>


    <div class="container">

        <!--  image left  -->
        <div class="row">
            @RenderBody()

        </div>
    </div>


    @RenderSection("Scripts", required: false)

    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.cards-gallery', { animation: 'slideIn' });
    </script>
</body>
</html>